// Code generated by protoc-gen-go.
// source: Slots.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	Slots.proto

It has these top-level messages:
	User
	Bet
	Result
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id    int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Money int32 `protobuf:"varint,2,opt,name=money" json:"money,omitempty"`
	Win   int32 `protobuf:"varint,3,opt,name=win" json:"win,omitempty"`
	Lose  int32 `protobuf:"varint,4,opt,name=lose" json:"lose,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *User) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *User) GetLose() int32 {
	if m != nil {
		return m.Lose
	}
	return 0
}

type Bet struct {
	Money int32 `protobuf:"varint,1,opt,name=money" json:"money,omitempty"`
}

func (m *Bet) Reset()                    { *m = Bet{} }
func (m *Bet) String() string            { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()               {}
func (*Bet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bet) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type Result struct {
	Ret   int32   `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Win   int32   `protobuf:"varint,2,opt,name=win" json:"win,omitempty"`
	Value []int32 `protobuf:"varint,3,rep,packed,name=value" json:"value,omitempty"`
	User  *User   `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *Result) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *Result) GetValue() []int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Result) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Bet)(nil), "pb.Bet")
	proto.RegisterType((*Result)(nil), "pb.Result")
}

func init() { proto.RegisterFile("Slots.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x69, 0x92, 0x16, 0xb9, 0x82, 0xc8, 0xd1, 0x21, 0xa0, 0x43, 0xe9, 0xe4, 0xd4, 0x41,
	0xdf, 0xc0, 0x47, 0x88, 0xb8, 0x6b, 0xe9, 0x0d, 0x85, 0xd8, 0x94, 0x24, 0x55, 0x7c, 0x7b, 0xc9,
	0xa9, 0xd4, 0xed, 0xff, 0xbf, 0x83, 0xef, 0xf8, 0xa1, 0x3c, 0x5b, 0x17, 0x43, 0x3b, 0x79, 0x17,
	0x1d, 0x8a, 0xa9, 0x6b, 0x0c, 0xa8, 0x4b, 0x20, 0x8f, 0x6b, 0x10, 0x43, 0xaf, 0xb3, 0x3a, 0xdb,
	0xe7, 0x46, 0x0c, 0x3d, 0x56, 0x90, 0xdf, 0xdd, 0x48, 0x2f, 0x2d, 0x18, 0x7d, 0x0a, 0x6e, 0x40,
	0x3e, 0x87, 0x51, 0x4b, 0x66, 0x29, 0x22, 0x82, 0xb2, 0x2e, 0x90, 0x56, 0x8c, 0x38, 0x37, 0x5b,
	0x90, 0x27, 0x8a, 0x8b, 0x22, 0xfb, 0x53, 0x34, 0x57, 0x28, 0x0c, 0x85, 0xd9, 0xc6, 0x24, 0xf3,
	0x14, 0xbf, 0xd7, 0x14, 0x7f, 0x7a, 0xb1, 0xe8, 0x2b, 0xc8, 0x1f, 0x37, 0x3b, 0x93, 0x96, 0xb5,
	0x4c, 0x0e, 0x2e, 0xb8, 0x03, 0x35, 0x07, 0xf2, 0xfc, 0xb4, 0x3c, 0xac, 0xda, 0xa9, 0x6b, 0xd3,
	0x08, 0xc3, 0xb4, 0x2b, 0x78, 0xdd, 0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x60, 0xce, 0x3a, 0x04,
	0xec, 0x00, 0x00, 0x00,
}
