// Code generated by protoc-gen-go.
// source: Person.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	Person.proto

It has these top-level messages:
	Person
	PhoneNumber
	User
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enum为关键字，作用为定义一种枚举类型
type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}
func (PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// message为关键字，作用为定义一种消息类型
type Person struct {
	Name   string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age    int32          `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Emails []string       `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
	Phones []*PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

// message为关键字，作用为定义一种消息类型可以被另外的消息类型嵌套使用
type PhoneNumber struct {
	Number string    `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   PhoneType `protobuf:"varint,2,opt,name=type,enum=pb.PhoneType" json:"type,omitempty"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

type User struct {
	Mid   int32   `protobuf:"varint,1,opt,name=mid" json:"mid,omitempty"`
	Money int32   `protobuf:"varint,2,opt,name=money" json:"money,omitempty"`
	Sex   int32   `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	Sicon string  `protobuf:"bytes,4,opt,name=sicon" json:"sicon,omitempty"`
	Vip   int32   `protobuf:"varint,5,opt,name=vip" json:"vip,omitempty"`
	Props []int32 `protobuf:"varint,6,rep,packed,name=props" json:"props,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetMid() int32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *User) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetSicon() string {
	if m != nil {
		return m.Sicon
	}
	return ""
}

func (m *User) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *User) GetProps() []int32 {
	if m != nil {
		return m.Props
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "pb.Person")
	proto.RegisterType((*PhoneNumber)(nil), "pb.PhoneNumber")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterEnum("pb.PhoneType", PhoneType_name, PhoneType_value)
}

func init() { proto.RegisterFile("Person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xed, 0x92, 0x06, 0x77, 0xe7, 0x9f, 0x12, 0x44, 0xf2, 0x58, 0xf7, 0x62, 0x51, 0xe8,
	0xc3, 0xfc, 0x06, 0xc2, 0x60, 0xa2, 0xb3, 0x23, 0x28, 0x3e, 0xb7, 0x7a, 0xd1, 0x82, 0x4d, 0x42,
	0x33, 0xc7, 0xfa, 0xe2, 0x67, 0x97, 0x9b, 0x94, 0xe1, 0xdb, 0x39, 0xf7, 0xfe, 0x72, 0xcf, 0x21,
	0x70, 0xb2, 0xc1, 0xde, 0x5b, 0x53, 0xba, 0xde, 0x6e, 0xad, 0x9c, 0xb8, 0x66, 0x6e, 0x41, 0xc4,
	0x99, 0x94, 0xc0, 0x4d, 0xdd, 0xa1, 0x4a, 0xf2, 0xa4, 0x98, 0xea, 0xa0, 0x65, 0x06, 0xac, 0xfe,
	0x44, 0x35, 0xc9, 0x93, 0x22, 0xd5, 0x24, 0xe5, 0x25, 0x08, 0xec, 0xea, 0xf6, 0xdb, 0x2b, 0x96,
	0xb3, 0x62, 0xaa, 0x47, 0x27, 0xaf, 0x41, 0xb8, 0x2f, 0x6b, 0xd0, 0x2b, 0x9e, 0xb3, 0x62, 0xb6,
	0x38, 0x2f, 0x5d, 0x53, 0x6e, 0x68, 0xf2, 0xfc, 0xd3, 0x35, 0xd8, 0xeb, 0x71, 0x3d, 0x5f, 0xc1,
	0xec, 0xdf, 0x98, 0xee, 0x99, 0xa0, 0xc6, 0xdc, 0xd1, 0xc9, 0x2b, 0xe0, 0xdb, 0xc1, 0xc5, 0xe8,
	0xb3, 0xc5, 0xe9, 0xe1, 0xda, 0xcb, 0xe0, 0x50, 0x87, 0xd5, 0xfc, 0x17, 0xf8, 0xab, 0xc7, 0x9e,
	0x4a, 0x76, 0xed, 0x47, 0x78, 0x9f, 0x6a, 0x92, 0xf2, 0x02, 0xd2, 0xce, 0x1a, 0x1c, 0xc6, 0xe2,
	0xd1, 0x10, 0xe7, 0x71, 0xaf, 0x58, 0xe4, 0x3c, 0xee, 0x89, 0xf3, 0xed, 0xbb, 0x35, 0x8a, 0x87,
	0xec, 0x68, 0x88, 0xdb, 0xb5, 0x4e, 0xa5, 0x91, 0xdb, 0xb5, 0x8e, 0x38, 0xd7, 0x5b, 0xe7, 0x95,
	0xc8, 0x19, 0xdd, 0x0b, 0xe6, 0xe6, 0x16, 0xa6, 0x87, 0x4a, 0x12, 0x40, 0xac, 0xab, 0xfb, 0x87,
	0xa7, 0x65, 0x76, 0x24, 0x8f, 0x81, 0xaf, 0xaa, 0xf5, 0x32, 0x4b, 0x48, 0xbd, 0x55, 0xfa, 0x31,
	0x9b, 0x34, 0x22, 0x7c, 0xf9, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x25, 0x99, 0x4c,
	0x82, 0x01, 0x00, 0x00,
}
